# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Access_Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData


class Ui_Access_Control(object):
    def setupUi(self, Access_Control):
        Access_Control.setObjectName("Access_Control")
        Access_Control.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(Access_Control)
        self.newWindow.setStyleSheet("*{\n"
        "    border:1px solid whilte;\n"
        "    border-radius:5px;\n"
        "}\n"
        "#newWindow,#consoleEdit{\n"
        "    background-color: #161f2b;\n"
        "}\n"
        "QCheckBox, QPushButton{\n"
        "    padding:2px 5px;\n"
        "}\n"
        "QLineEdit{background-color: rgba(0,0,0,0);\n"
        "    border:none;\n"
        "    border-bottom:2px solid rgba(46,82,101,200);\n"
        "    color: rgb(214, 214, 214);\n"
        "    padding-bottom:7px;\n"
        "}\n"
        "#buttons{\n"
        "    border:none;}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 0, 0, 1, 7)
        self.fmpmpswrd = QtWidgets.QLineEdit(self.InputFrame)
        self.fmpmpswrd.setObjectName("fmpmpswrd")
        self.gridLayout.addWidget(self.fmpmpswrd, 1, 6, 1, 1)
        self.buttons = QtWidgets.QFrame(self.InputFrame)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.S_all = QtWidgets.QCheckBox(self.buttons)
        self.S_all.setObjectName("S_all")
        self.horizontalLayout.addWidget(self.S_all)
        self.runButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.submitBtn = QtWidgets.QPushButton(self.buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.horizontalLayout.addWidget(self.submitBtn)
        self.gridLayout.addWidget(self.buttons, 10, 0, 1, 7, QtCore.Qt.AlignHCenter)
        self.fmpmuser = QtWidgets.QLineEdit(self.InputFrame)
        self.fmpmuser.setObjectName("fmpmuser")
        self.gridLayout.addWidget(self.fmpmuser, 1, 5, 1, 1)
        self.sudouser = QtWidgets.QLineEdit(self.InputFrame)
        self.sudouser.setObjectName("sudouser")
        self.gridLayout.addWidget(self.sudouser, 1, 0, 1, 1)
        self.nmspswrd = QtWidgets.QLineEdit(self.InputFrame)
        self.nmspswrd.setObjectName("nmspswrd")
        self.gridLayout.addWidget(self.nmspswrd, 1, 4, 1, 1)
        self.nmsuser = QtWidgets.QLineEdit(self.InputFrame)
        self.nmsuser.setText("")
        self.nmsuser.setObjectName("nmsuser")
        self.gridLayout.addWidget(self.nmsuser, 1, 3, 1, 1)
        self.sudopswrd = QtWidgets.QLineEdit(self.InputFrame)
        self.sudopswrd.setObjectName("sudopswrd")
        self.gridLayout.addWidget(self.sudopswrd, 1, 2, 1, 1)
        self.TC_018 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_018.setStyleSheet("")
        self.TC_018.setObjectName("TC_018")
        self.gridLayout.addWidget(self.TC_018, 2, 0, 1, 1)
        self.TC_019 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_019.setObjectName("TC_019")
        self.gridLayout.addWidget(self.TC_019, 2, 2, 1, 1)
        self.TC_020 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_020.setObjectName("TC_020")
        self.gridLayout.addWidget(self.TC_020, 2, 3, 1, 1)
        self.TC_021 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_021.setObjectName("TC_021")
        self.gridLayout.addWidget(self.TC_021, 2, 4, 1, 1)
        self.TC_022 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_022.setObjectName("TC_022")
        self.gridLayout.addWidget(self.TC_022, 2, 5, 1, 1)
        self.TC_023 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_023.setObjectName("TC_023")
        self.gridLayout.addWidget(self.TC_023, 2, 6, 1, 1)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        Access_Control.setCentralWidget(self.newWindow)

        self.retranslateUi(Access_Control)
        QtCore.QMetaObject.connectSlotsByName(Access_Control)

    def retranslateUi(self, Access_Control):
        _translate = QtCore.QCoreApplication.translate
        Access_Control.setWindowTitle(_translate("Access_Control", "MainWindow"))
        self.InputLabel.setText(_translate("Access_Control", "Test Cases and User Input"))
        self.fmpmpswrd.setPlaceholderText(_translate("Access_Control", "fm-pm password"))
        self.S_all.setText(_translate("Access_Control", "Select All"))
        self.runButton.setText(_translate("Access_Control", "RUN"))
        self.submitBtn.setText(_translate("Access_Control", "Submit"))
        self.fmpmuser.setPlaceholderText(_translate("Access_Control", "fm-pm username"))
        self.sudouser.setPlaceholderText(_translate("Access_Control", "Sudo Username"))
        self.nmspswrd.setPlaceholderText(_translate("Access_Control", "NMS Password"))
        self.nmsuser.setPlaceholderText(_translate("Access_Control", "NMS Username"))
        self.sudopswrd.setPlaceholderText(_translate("Access_Control", "Sudo Password"))
        self.TC_018.setText(_translate("Access_Control", "M_CTC_ID_018"))
        self.TC_019.setText(_translate("Access_Control", "M_CTC_ID_019"))
        self.TC_020.setText(_translate("Access_Control", "M_CTC_ID_020"))
        self.TC_021.setText(_translate("Access_Control", "M_CTC_ID_021"))
        self.TC_022.setText(_translate("Access_Control", "M_CTC_ID_022"))
        self.TC_023.setText(_translate("Access_Control", "M_CTC_ID_023"))
        self.outputLabel.setText(_translate("Access_Control", "Output"))

    def get_data(self):
        print(self.sudouser.text())
        print(self.sudopswrd.text())
        print(self.nmsuser.text())
        print(self.nmspswrd.text())
        print(self.fmpmuser.text())
        print(self.fmpmpswrd.text())
        data = {'SUDO_USER' : self.sudouser.text(), 'SUDO_PASS' : self.sudopswrd.text(),
                'NMS_USER' : self.nmsuser.text(), 'NMS_PASS' : self.nmspswrd.text(),
                'FMPM_USER' : self.fmpmuser.text(), 'FMPM_PASS' : self.fmpmpswrd.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Access_Control = QtWidgets.QMainWindow()
    ui = Ui_Access_Control()
    ui.setupUi(Access_Control)
    Access_Control.show()
    sys.exit(app.exec_())
