# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_Subscribe.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData


class Ui_Create_Subscribe(object):
    def setupUi(self, Create_Subscribe):
        Create_Subscribe.setObjectName("Create_Subscribe")
        Create_Subscribe.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(Create_Subscribe)
        self.newWindow.setStyleSheet("*{\n"
"    border:1px solid whilte;\n"
"    border-radius:5px;\n"
"}\n"
"#newWindow,#consoleEdit{\n"
"    background-color: #161f2b;\n"
"}\n"
"QCheckBox, QPushButton,QLineEdit{\n"
"    padding:2px 5px;\n"
"}\n"
"QLineEdit{background-color: rgba(0,0,0,0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(46,82,101,200);\n"
"    color: rgb(214, 214, 214);\n"
"    padding-bottom:7px;\n"
"}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 1, 0, 1, 3)
        self.paragon_ip = QtWidgets.QLineEdit(self.InputFrame)
        self.paragon_ip.setObjectName("paragon_ip")
        self.gridLayout.addWidget(self.paragon_ip, 4, 1, 1, 1)
        self.ptpSyncE = QtWidgets.QLineEdit(self.InputFrame)
        self.ptpSyncE.setObjectName("ptpSyncE")
        self.gridLayout.addWidget(self.ptpSyncE, 4, 2, 1, 1)
        self.Buttons = QtWidgets.QFrame(self.InputFrame)
        self.Buttons.setStyleSheet("#Buttons{\n"
"border:none;\n"
"}")
        self.Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.Buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.submitBtn = QtWidgets.QPushButton(self.Buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.horizontalLayout.addWidget(self.submitBtn)
        self.gridLayout.addWidget(self.Buttons, 5, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.password = QtWidgets.QLineEdit(self.InputFrame)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 3, 2, 1, 1)
        self.username = QtWidgets.QLineEdit(self.InputFrame)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        Create_Subscribe.setCentralWidget(self.newWindow)

        self.retranslateUi(Create_Subscribe)
        QtCore.QMetaObject.connectSlotsByName(Create_Subscribe)

    def retranslateUi(self, Create_Subscribe):
        _translate = QtCore.QCoreApplication.translate
        Create_Subscribe.setWindowTitle(_translate("Create_Subscribe", "MainWindow"))
        self.InputLabel.setText(_translate("Create_Subscribe", "Test Cases and User Input"))
        self.paragon_ip.setPlaceholderText(_translate("Create_Subscribe", "Paragon Neo IP"))
        self.ptpSyncE.setPlaceholderText(_translate("Create_Subscribe", "PTP & SyncE Port"))
        self.runButton.setText(_translate("Create_Subscribe", "M_CTC_ID_007"))
        self.submitBtn.setText(_translate("Create_Subscribe", "Submit"))
        self.password.setPlaceholderText(_translate("Create_Subscribe", "Sudo Password"))
        self.username.setPlaceholderText(_translate("Create_Subscribe", "Sudo Username"))
        self.outputLabel.setText(_translate("Create_Subscribe", "Output"))

    def get_data(self):
        print(self.username.text())
        print(self.password.text())
        print(self.paragon_ip.text())
        print(self.ptpSyncE.text())
        data = {'SUDO_USER' : self.username.text(), 'SUDO_PASS' : self.password.text(), 
            'paragon_ip' : self.paragon_ip.text(),'ptpSyncEport' : self.ptpSyncE.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create_Subscribe = QtWidgets.QMainWindow()
    ui = Ui_Create_Subscribe()
    ui.setupUi(Create_Subscribe)
    Create_Subscribe.show()
    sys.exit(app.exec_())
