# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fault_Mgmt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData


class Ui_Fault_Mgmt(object):
    def setupUi(self, Fault_Mgmt):
        Fault_Mgmt.setObjectName("Fault_Mgmt")
        Fault_Mgmt.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(Fault_Mgmt)
        self.newWindow.setStyleSheet("*{\n"
"    border:1px solid whilte;\n"
"    border-radius:5px;\n"
"}\n"
"#newWindow,#consoleEdit{\n"
"    background-color: #161f2b;\n"
"}\n"
"QCheckBox, QPushButton{\n"
"    padding:2px 5px;\n"
"}\n"
"QLineEdit{background-color: rgba(0,0,0,0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(46,82,101,200);\n"
"    color: rgb(214, 214, 214);\n"
"    padding-bottom:7px;\n"
"}\n"
"#buttons{\n"
"    border: none;}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.password = QtWidgets.QLineEdit(self.InputFrame)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(self.InputFrame)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 0, 1, 1)
        self.p_neoIP = QtWidgets.QLineEdit(self.InputFrame)
        self.p_neoIP.setObjectName("p_neoIP")
        self.gridLayout.addWidget(self.p_neoIP, 3, 0, 1, 1)
        self.ptpPort = QtWidgets.QLineEdit(self.InputFrame)
        self.ptpPort.setObjectName("ptpPort")
        self.gridLayout.addWidget(self.ptpPort, 3, 1, 1, 1)
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 0, 0, 1, 2)
        self.TC_013 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_013.setObjectName("TC_013")
        self.gridLayout.addWidget(self.TC_013, 4, 1, 1, 1)
        self.TC_012 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_012.setObjectName("TC_012")
        self.gridLayout.addWidget(self.TC_012, 4, 0, 1, 1)
        self.buttons = QtWidgets.QFrame(self.InputFrame)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.S_all = QtWidgets.QCheckBox(self.buttons)
        self.S_all.setObjectName("S_all")
        self.horizontalLayout.addWidget(self.S_all)
        self.runButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.submitBtn = QtWidgets.QPushButton(self.buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.horizontalLayout.addWidget(self.submitBtn)
        self.gridLayout.addWidget(self.buttons, 5, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        Fault_Mgmt.setCentralWidget(self.newWindow)

        self.retranslateUi(Fault_Mgmt)
        QtCore.QMetaObject.connectSlotsByName(Fault_Mgmt)

    def retranslateUi(self, Fault_Mgmt):
        _translate = QtCore.QCoreApplication.translate
        Fault_Mgmt.setWindowTitle(_translate("Fault_Mgmt", "MainWindow"))
        self.password.setPlaceholderText(_translate("Fault_Mgmt", "Sudo Password"))
        self.username.setPlaceholderText(_translate("Fault_Mgmt", "Sudo Username"))
        self.p_neoIP.setPlaceholderText(_translate("Fault_Mgmt", "Paragon Neo IP"))
        self.ptpPort.setPlaceholderText(_translate("Fault_Mgmt", "PTP & SyncE Port"))
        self.InputLabel.setText(_translate("Fault_Mgmt", "Test Cases and User Input"))
        self.TC_013.setText(_translate("Fault_Mgmt", "M_CTC_ID_013"))
        self.TC_012.setText(_translate("Fault_Mgmt", "M_CTC_ID_012"))
        self.S_all.setText(_translate("Fault_Mgmt", "Select All"))
        self.runButton.setText(_translate("Fault_Mgmt", "RUN"))
        self.submitBtn.setText(_translate("Fault_Mgmt", "Submit"))
        self.outputLabel.setText(_translate("Fault_Mgmt", "Output"))

    def get_data(self):
        print(self.username.text())
        print(self.password.text())
        print(self.p_neoIP.text())
        print(self.ptpPort.text())
        data = {'SUDO_USER' : self.username.text(), 'SUDO_PASS' : self.password.text(), 
            'paragon_ip' : self.p_neoIP.text(),'ptpSyncEport' : self.ptpPort.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fault_Mgmt = QtWidgets.QMainWindow()
    ui = Ui_Fault_Mgmt()
    ui.setupUi(Fault_Mgmt)
    Fault_Mgmt.show()
    sys.exit(app.exec_())
