# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Log_Mgmt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData


class Ui_Log_Mgmt(object):
    def setupUi(self, Log_Mgmt):
        Log_Mgmt.setObjectName("Log_Mgmt")
        Log_Mgmt.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(Log_Mgmt)
        self.newWindow.setStyleSheet("*{\n"
"    border:1px solid whilte;\n"
"    border-radius:5px;\n"
"}\n"
"#newWindow,#consoleEdit{\n"
"    background-color: #161f2b;\n"
"}\n"
"QCheckBox, QPushButton{\n"
"    padding:2px 5px;\n"
"}\n"
"QLineEdit{background-color: rgba(0,0,0,0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(46,82,101,200);\n"
"    color: rgb(214, 214, 214);\n"
"    padding-bottom:7px;\n"
"}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(self.InputFrame)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.InputFrame)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 0, 0, 1, 2)
        self.runBtn = QtWidgets.QPushButton(self.InputFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runBtn.setIcon(icon)
        self.runBtn.setObjectName("runBtn")
        self.gridLayout.addWidget(self.runBtn, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.submitBtn = QtWidgets.QPushButton(self.InputFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.gridLayout.addWidget(self.submitBtn, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        Log_Mgmt.setCentralWidget(self.newWindow)

        self.retranslateUi(Log_Mgmt)
        QtCore.QMetaObject.connectSlotsByName(Log_Mgmt)

    def retranslateUi(self, Log_Mgmt):
        _translate = QtCore.QCoreApplication.translate
        Log_Mgmt.setWindowTitle(_translate("Log_Mgmt", "MainWindow"))
        self.username.setPlaceholderText(_translate("Log_Mgmt", "Sudo Username"))
        self.password.setPlaceholderText(_translate("Log_Mgmt", "Sudo Password"))
        self.InputLabel.setText(_translate("Log_Mgmt", "Test Cases and User Input"))
        self.runBtn.setText(_translate("Log_Mgmt", "M_CTC_ID_034"))
        self.submitBtn.setText(_translate("Log_Mgmt", "Submit"))
        self.outputLabel.setText(_translate("Log_Mgmt", "Output"))

    def get_data(self):
        print(self.username.text())
        print(self.password.text())
        data = {'SUDO_USER' : self.username.text(), 'SUDO_PASS' : self.password.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Log_Mgmt = QtWidgets.QMainWindow()
    ui = Ui_Log_Mgmt()
    ui.setupUi(Log_Mgmt)
    Log_Mgmt.show()
    sys.exit(app.exec_())
