# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RU_Configurability.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData


class Ui_RU_Config(object):
    def setupUi(self, RU_Config):
        RU_Config.setObjectName("RU_Config")
        RU_Config.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(RU_Config)
        self.newWindow.setStyleSheet("*{\n"
"    border:1px solid whilte;\n"
"    border-radius:5px;\n"
"}\n"
"#newWindow,#consoleEdit{\n"
"    background-color: #161f2b;\n"
"}\n"
"QCheckBox, QPushButton{\n"
"    padding:2px 5px;\n"
"}\n"
"QLineEdit{background-color: rgba(0,0,0,0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(46,82,101,200);\n"
"    color: rgb(214, 214, 214);\n"
"    padding-bottom:7px;\n"
"}\n"
"#buttons{\n"
"    border:none;\n"
"}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.sudopswrd = QtWidgets.QLineEdit(self.InputFrame)
        self.sudopswrd.setObjectName("sudopswrd")
        self.gridLayout.addWidget(self.sudopswrd, 1, 1, 1, 1)
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 0, 0, 1, 3)
        self.TC_027 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_027.setObjectName("TC_027")
        self.gridLayout.addWidget(self.TC_027, 5, 1, 1, 1)
        self.S_all = QtWidgets.QCheckBox(self.InputFrame)
        self.S_all.setObjectName("S_all")
        self.gridLayout.addWidget(self.S_all, 5, 2, 1, 1)
        self.sudouser = QtWidgets.QLineEdit(self.InputFrame)
        self.sudouser.setObjectName("sudouser")
        self.gridLayout.addWidget(self.sudouser, 1, 0, 1, 1)
        self.TC_026 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_026.setStyleSheet("")
        self.TC_026.setObjectName("TC_026")
        self.gridLayout.addWidget(self.TC_026, 5, 0, 1, 1)
        self.fronhaulInterface = QtWidgets.QLineEdit(self.InputFrame)
        self.fronhaulInterface.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fronhaulInterface.setObjectName("fronhaulInterface")
        self.gridLayout.addWidget(self.fronhaulInterface, 1, 2, 1, 1)
        self.buttons = QtWidgets.QFrame(self.InputFrame)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.submitBtn = QtWidgets.QPushButton(self.buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.horizontalLayout.addWidget(self.submitBtn)
        self.gridLayout.addWidget(self.buttons, 6, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        RU_Config.setCentralWidget(self.newWindow)

        self.retranslateUi(RU_Config)
        QtCore.QMetaObject.connectSlotsByName(RU_Config)

    def retranslateUi(self, RU_Config):
        _translate = QtCore.QCoreApplication.translate
        RU_Config.setWindowTitle(_translate("RU_Config", "MainWindow"))
        self.sudopswrd.setPlaceholderText(_translate("RU_Config", "Sudo Password"))
        self.InputLabel.setText(_translate("RU_Config", "Test Cases and User Input"))
        self.TC_027.setText(_translate("RU_Config", "M_CTC_ID_027"))
        self.S_all.setText(_translate("RU_Config", "Select All"))
        self.sudouser.setPlaceholderText(_translate("RU_Config", "Sudo Username"))
        self.TC_026.setText(_translate("RU_Config", "M_CTC_ID_026"))
        self.fronhaulInterface.setPlaceholderText(_translate("RU_Config", "RU Fronthoul Interface Name"))
        self.runButton.setText(_translate("RU_Config", "RUN"))
        self.submitBtn.setText(_translate("RU_Config", "Submit"))
        self.outputLabel.setText(_translate("RU_Config", "Output"))

    def get_data(self):
        print(self.sudouser.text())
        print(self.sudopswrd.text())
        print(self.fronhaulInterface.text())
        data = {'SUDO_USER' : self.sudouser.text(), 'SUDO_PASS' : self.sudopswrd.text(),
                'FH_Interface' : self.fronhaulInterface.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RU_Config = QtWidgets.QMainWindow()
    ui = Ui_RU_Config()
    ui.setupUi(RU_Config)
    RU_Config.show()
    sys.exit(app.exec_())
