# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SW_Mgmt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData


class Ui_SW_Mgmt(object):
    def setupUi(self, SW_Mgmt):
        SW_Mgmt.setObjectName("SW_Mgmt")
        SW_Mgmt.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(SW_Mgmt)
        self.newWindow.setStyleSheet("*{\n"
"    border:1px solid whilte;\n"
"    border-radius:5px;\n"
"}\n"
"#newWindow,#consoleEdit{\n"
"    background-color: #161f2b;\n"
"}\n"
"QCheckBox, QPushButton{\n"
"    padding:2px 5px;\n"
"}\n"
"QLineEdit{background-color: rgba(0,0,0,0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(46,82,101,200);\n"
"    color: rgb(214, 214, 214);\n"
"    padding-bottom:7px;\n"
"}\n"
"#buttons{\n"
"    border:none;}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.TC_015 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_015.setObjectName("TC_015")
        self.gridLayout.addWidget(self.TC_015, 7, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(self.InputFrame)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 2, 1, 2)
        self.du_pswrd = QtWidgets.QLineEdit(self.InputFrame)
        self.du_pswrd.setObjectName("du_pswrd")
        self.gridLayout.addWidget(self.du_pswrd, 2, 0, 1, 2)
        self.TC_016 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_016.setObjectName("TC_016")
        self.gridLayout.addWidget(self.TC_016, 7, 2, 1, 1)
        self.TC_014 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_014.setStyleSheet("")
        self.TC_014.setObjectName("TC_014")
        self.gridLayout.addWidget(self.TC_014, 7, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.InputFrame)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 0, 1, 2)
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 0, 0, 1, 4)
        self.TC_017 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_017.setObjectName("TC_017")
        self.gridLayout.addWidget(self.TC_017, 7, 3, 1, 1)
        self.sw_file = QtWidgets.QLineEdit(self.InputFrame)
        self.sw_file.setObjectName("sw_file")
        self.gridLayout.addWidget(self.sw_file, 2, 2, 1, 2)
        self.currupt_file = QtWidgets.QLineEdit(self.InputFrame)
        self.currupt_file.setAlignment(QtCore.Qt.AlignCenter)
        self.currupt_file.setObjectName("currupt_file")
        self.gridLayout.addWidget(self.currupt_file, 3, 0, 1, 4)
        self.buttons = QtWidgets.QFrame(self.InputFrame)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.S_all = QtWidgets.QCheckBox(self.buttons)
        self.S_all.setObjectName("S_all")
        self.horizontalLayout.addWidget(self.S_all)
        self.runButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.submitBtn = QtWidgets.QPushButton(self.buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.horizontalLayout.addWidget(self.submitBtn)
        self.gridLayout.addWidget(self.buttons, 8, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        SW_Mgmt.setCentralWidget(self.newWindow)

        self.retranslateUi(SW_Mgmt)
        QtCore.QMetaObject.connectSlotsByName(SW_Mgmt)

    def retranslateUi(self, SW_Mgmt):
        _translate = QtCore.QCoreApplication.translate
        SW_Mgmt.setWindowTitle(_translate("SW_Mgmt", "MainWindow"))
        self.TC_015.setText(_translate("SW_Mgmt", "M_CTC_ID_015"))
        self.username.setPlaceholderText(_translate("SW_Mgmt", "Sudo Password"))
        self.du_pswrd.setPlaceholderText(_translate("SW_Mgmt", "DU Password"))
        self.TC_016.setText(_translate("SW_Mgmt", "M_CTC_ID_016"))
        self.TC_014.setText(_translate("SW_Mgmt", "M_CTC_ID_014"))
        self.password.setPlaceholderText(_translate("SW_Mgmt", "Sudo Username"))
        self.InputLabel.setText(_translate("SW_Mgmt", "Test Cases and User Input"))
        self.TC_017.setText(_translate("SW_Mgmt", "M_CTC_ID_017"))
        self.sw_file.setPlaceholderText(_translate("SW_Mgmt", "Software File Path"))
        self.currupt_file.setPlaceholderText(_translate("SW_Mgmt", "Currupt File Path"))
        self.S_all.setText(_translate("SW_Mgmt", "Select All"))
        self.runButton.setText(_translate("SW_Mgmt", "RUN"))
        self.submitBtn.setText(_translate("SW_Mgmt", "Submit"))
        self.outputLabel.setText(_translate("SW_Mgmt", "Output"))

    def get_data(self):
        print(self.username.text())
        print(self.password.text())
        print(self.du_pswrd.text())
        print(self.sw_file.text())
        print(self.currupt_file.text())
        data = {'SUDO_USER' : self.username.text(), 'SUDO_PASS' : self.password.text(),
                'DU_PASS' : self.du_pswrd.text(), 'SW_PATH' : self.sw_file.text(),
                'Currupt_Path' : self.currupt_file.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SW_Mgmt = QtWidgets.QMainWindow()
    ui = Ui_SW_Mgmt()
    ui.setupUi(SW_Mgmt)
    SW_Mgmt.show()
    sys.exit(app.exec_())
