# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransportHandshake.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import resource

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print(dir_path)
sys.path.append(dir_path)
from require.Write_Data import WriteData



class Ui_TransportHandshake(object):
    def setupUi(self, TransportHandshake):
        TransportHandshake.setObjectName("TransportHandshake")
        TransportHandshake.resize(655, 544)
        self.newWindow = QtWidgets.QWidget(TransportHandshake)
        self.newWindow.setGeometry(0,60,100,30)
        self.newWindow.setStyleSheet("*{\n"
        "    border:1px solid whilte;\n"
        "    border-radius:5px;\n"
        "}\n"
        "#newWindow,#consoleEdit{\n"
        "    background-color: #161f2b;\n"
        "}\n"
        "QCheckBox, QPushButton{\n"
        "    padding:2px 5px;\n"
        "}\n"
        "QLineEdit{background-color: rgba(0,0,0,0);\n"
        "    border:none;\n"
        "    border-bottom:2px solid rgba(46,82,101,200);\n"
        "    color: rgb(214, 214, 214);\n"
        "    padding-bottom:7px;\n"
        "}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.TC_001 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_001.setStyleSheet("")
        self.TC_001.setObjectName("TC_001")
        self.gridLayout.addWidget(self.TC_001, 2, 0, 1, 1)
        self.TC_002 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_002.setObjectName("TC_002")
        self.gridLayout.addWidget(self.TC_002, 2, 1, 1, 1)
        self.TC_003 = QtWidgets.QCheckBox(self.InputFrame)
        self.TC_003.setObjectName("TC_003")
        self.gridLayout.addWidget(self.TC_003, 2, 2, 1, 1)
        self.S_all = QtWidgets.QCheckBox(self.InputFrame)
        self.S_all.setObjectName("S_all")
        self.gridLayout.addWidget(self.S_all, 2, 3, 1, 1)
        self.input1 = QtWidgets.QLineEdit(self.InputFrame)
        self.input1.setObjectName("input1")
        self.gridLayout.addWidget(self.input1, 1, 0, 1, 2)
        self.input = QtWidgets.QLineEdit(self.InputFrame)
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 1, 2, 1, 2)
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.gridLayout.addWidget(self.InputLabel, 0, 0, 1, 4)
        self.buttons = QtWidgets.QFrame(self.InputFrame)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.buttons.setStyleSheet("#buttons{\n"
"border:none;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.submitBtn = QtWidgets.QPushButton(self.buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon1)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.clicked.connect(self.get_data)
        self.horizontalLayout.addWidget(self.submitBtn)
        self.gridLayout.addWidget(self.buttons, 6, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        TransportHandshake.setCentralWidget(self.newWindow)

        self.retranslateUi(TransportHandshake)
        QtCore.QMetaObject.connectSlotsByName(TransportHandshake)

    def retranslateUi(self, TransportHandshake):
        _translate = QtCore.QCoreApplication.translate
        TransportHandshake.setWindowTitle(_translate("TransportHandshake", "MainWindow"))
        self.TC_001.setText(_translate("TransportHandshake", "M_CTC_ID_001"))
        self.TC_002.setText(_translate("TransportHandshake", "M_CTC_ID_002"))
        self.TC_003.setText(_translate("TransportHandshake", "M_CTC_ID_003"))
        self.S_all.setText(_translate("TransportHandshake", "Select All"))
        self.input1.setPlaceholderText(_translate("TransportHandshake", "Sudo Username"))
        self.input.setPlaceholderText(_translate("TransportHandshake", "Sudo Password"))
        self.InputLabel.setText(_translate("TransportHandshake", "Test Cases and User Input"))
        self.runButton.setText(_translate("TransportHandshake", "RUN"))
        self.submitBtn.setText(_translate("TransportHandshake", "Submit"))
        self.outputLabel.setText(_translate("TransportHandshake", "Output"))

    def get_data(self):
        print(self.input.text())
        print(self.input1.text())
        data = {'SUDO_USER' : self.input1.text(), 'SUDO_PASS' : self.input.text()}
        WriteData(data,'{}/Conformance/inputs.ini'.format(dir_path))
        pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TransportHandshake = QtWidgets.QMainWindow()
    ui = Ui_TransportHandshake()
    ui.setupUi(TransportHandshake)
    TransportHandshake.show()
    sys.exit(app.exec_())
