# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup(QtWidgets.QMainWindow):
    # def __init__(self):
    #     QtWidgets.QMainWindow.__init__(self)
    
    def pop_up_message(self,message):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle('PopUp')
        msg.resize(600,100)
        msg.setText('{}.'.format(message))
        msg.exec_()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication([])
    ui = Ui_popup()
    ui.pop_up_message('Please Change the Compression')