# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run_all.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Access_Control(object):
    def setupUi(self, Access_Control):
        Access_Control.setObjectName("Access_Control")
        Access_Control.resize(638, 544)
        self.newWindow = QtWidgets.QWidget(Access_Control)
        self.newWindow.setStyleSheet("*{\n"
"    border:1px solid whilte;\n"
"    border-radius:5px;\n"
"}\n"
"#newWindow,#consoleEdit{\n"
"    background-color: #161f2b;\n"
"}\n"
"QCheckBox, QPushButton{\n"
"    padding:2px 5px;\n"
"}\n"
"QLineEdit{background-color: rgba(0,0,0,0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(46,82,101,200);\n"
"    color: rgb(214, 214, 214);\n"
"    padding-bottom:7px;\n"
"}\n"
"#buttons,#input_frame{\n"
"    border:none;}")
        self.newWindow.setObjectName("newWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputFrame = QtWidgets.QFrame(self.newWindow)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.InputFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InputLabel = QtWidgets.QLabel(self.InputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InputLabel.setFont(font)
        self.InputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLabel.setObjectName("InputLabel")
        self.verticalLayout_3.addWidget(self.InputLabel)
        self.input_frame = QtWidgets.QFrame(self.InputFrame)
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_02 = QtWidgets.QLineEdit(self.input_frame)
        self.input_02.setObjectName("input_02")
        self.gridLayout_2.addWidget(self.input_02, 0, 1, 1, 1)
        self.input_11 = QtWidgets.QLineEdit(self.input_frame)
        self.input_11.setText("")
        self.input_11.setObjectName("input_11")
        self.gridLayout_2.addWidget(self.input_11, 1, 7, 1, 1)
        self.input_03 = QtWidgets.QLineEdit(self.input_frame)
        self.input_03.setText("")
        self.input_03.setObjectName("input_03")
        self.gridLayout_2.addWidget(self.input_03, 0, 3, 1, 1)
        self.input_06 = QtWidgets.QLineEdit(self.input_frame)
        self.input_06.setObjectName("input_06")
        self.gridLayout_2.addWidget(self.input_06, 0, 9, 1, 1)
        self.input_01 = QtWidgets.QLineEdit(self.input_frame)
        self.input_01.setObjectName("input_01")
        self.gridLayout_2.addWidget(self.input_01, 0, 0, 1, 1)
        self.input_04 = QtWidgets.QLineEdit(self.input_frame)
        self.input_04.setObjectName("input_04")
        self.gridLayout_2.addWidget(self.input_04, 0, 5, 1, 1)
        self.input_05 = QtWidgets.QLineEdit(self.input_frame)
        self.input_05.setObjectName("input_05")
        self.gridLayout_2.addWidget(self.input_05, 0, 7, 1, 1)
        self.input_09 = QtWidgets.QLineEdit(self.input_frame)
        self.input_09.setObjectName("input_09")
        self.gridLayout_2.addWidget(self.input_09, 1, 3, 1, 1)
        self.input_12 = QtWidgets.QLineEdit(self.input_frame)
        self.input_12.setObjectName("input_12")
        self.gridLayout_2.addWidget(self.input_12, 1, 9, 1, 1)
        self.input_07 = QtWidgets.QLineEdit(self.input_frame)
        self.input_07.setObjectName("input_07")
        self.gridLayout_2.addWidget(self.input_07, 1, 0, 1, 1)
        self.input_08 = QtWidgets.QLineEdit(self.input_frame)
        self.input_08.setObjectName("input_08")
        self.gridLayout_2.addWidget(self.input_08, 1, 1, 1, 1)
        self.input_10 = QtWidgets.QLineEdit(self.input_frame)
        self.input_10.setObjectName("input_10")
        self.gridLayout_2.addWidget(self.input_10, 1, 5, 1, 1)
        self.input_13 = QtWidgets.QLineEdit(self.input_frame)
        self.input_13.setObjectName("input_13")
        self.gridLayout_2.addWidget(self.input_13, 2, 0, 1, 4)
        self.input_14 = QtWidgets.QLineEdit(self.input_frame)
        self.input_14.setObjectName("input_14")
        self.gridLayout_2.addWidget(self.input_14, 2, 5, 1, 5)
        self.verticalLayout_3.addWidget(self.input_frame)
        self.buttons = QtWidgets.QFrame(self.InputFrame)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.submitBtn = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitBtn.setIcon(icon)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout.addWidget(self.submitBtn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.buttons)
        self.verticalLayout.addWidget(self.InputFrame)
        self.OutputFrame = QtWidgets.QFrame(self.newWindow)
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.OutputFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel, 0, QtCore.Qt.AlignTop)
        self.consoleEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.verticalLayout.addWidget(self.OutputFrame)
        Access_Control.setCentralWidget(self.newWindow)

        self.retranslateUi(Access_Control)
        QtCore.QMetaObject.connectSlotsByName(Access_Control)

    def retranslateUi(self, Access_Control):
        _translate = QtCore.QCoreApplication.translate
        Access_Control.setWindowTitle(_translate("Access_Control", "MainWindow"))
        self.InputLabel.setText(_translate("Access_Control", "Test Cases and User Input"))
        self.input_02.setPlaceholderText(_translate("Access_Control", "Sudo Password"))
        self.input_11.setPlaceholderText(_translate("Access_Control", "TX Arfcn"))
        self.input_03.setPlaceholderText(_translate("Access_Control", "NMS Username"))
        self.input_06.setPlaceholderText(_translate("Access_Control", "fm-pm password"))
        self.input_01.setPlaceholderText(_translate("Access_Control", "Sudo Username"))
        self.input_04.setPlaceholderText(_translate("Access_Control", "NMS Password"))
        self.input_05.setPlaceholderText(_translate("Access_Control", "fm-pm username"))
        self.input_09.setPlaceholderText(_translate("Access_Control", "RU Fronthaul Interface Name"))
        self.input_12.setPlaceholderText(_translate("Access_Control", "RX Arfcn"))
        self.input_07.setPlaceholderText(_translate("Access_Control", "Paragon IP"))
        self.input_08.setPlaceholderText(_translate("Access_Control", "PTP & SYNCE Port"))
        self.input_10.setPlaceholderText(_translate("Access_Control", "Bandwidth"))
        self.input_13.setPlaceholderText(_translate("Access_Control", "Software File Path"))
        self.input_14.setPlaceholderText(_translate("Access_Control", "Currupt FIle Path"))
        self.submitBtn.setText(_translate("Access_Control", "Submit"))
        self.outputLabel.setText(_translate("Access_Control", "Output"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Access_Control = QtWidgets.QMainWindow()
    ui = Ui_Access_Control()
    ui.setupUi(Access_Control)
    Access_Control.show()
    sys.exit(app.exec_())
