# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_M.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QProcess
from PyQt5.QtWidgets import *


import re ,os

progress_re = re.compile("Total complete: (\d+)%")

def simple_percent_parser(output):
    """
    Matches lines using the progress_re regex,
    returning a single integer for the % progress.
    """
    m = progress_re.search(output)
    if m:
        pc_complete = m.group(1)
        return int(pc_complete)


class Ui_MainWindow(object):
    # def openWindow(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_Menu()
    #     self.ui.setupUi(self.window)
 
    #     self.window.close()

    def setupUi(self, MainWindow):
        self.p = None
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout.setObjectName("formLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"border-color: #050a0e;\n"
"border-width: 1px;\n"
"border-radius: 5px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_7)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
#         self.frame_4 = QtWidgets.QFrame(self.frame)
#         self.frame_4.setStyleSheet("background-color: rgb(21, 26, 30);\n"
# "border-color: #050a0e;\n"
# "border-width: 1px;\n"
# "border-radius: 5px;")
#         self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.frame_4.setObjectName("frame_4")
        # self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        # self.gridLayout.setObjectName("gridLayout")
        # self.label = QtWidgets.QLabel(self.frame_4)
        # self.label.setStyleSheet("color: rgb(255, 255, 255);")
        # self.label.setObjectName("label")
        # self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        # self.horizontalLayout.addWidget(self.frame_4)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_15)
        self.comboBox_1 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("SELECT RU TYPE")
        self.comboBox_1.addItem("SMALL_CELL")
        self.comboBox_1.addItem("MACRO_CELL")
        self.gridLayout_3.addWidget(self.comboBox_1, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_15)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
#         self.frame_10 = QtWidgets.QFrame(self.frame)
#         self.frame_10.setStyleSheet("background-color: rgb(21, 26, 30);\n"
# "border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;")
#         self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.frame_10.setObjectName("frame_10")
#         self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_10)
#         self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
#         self.gridLayout_3.setSpacing(0)
#         self.gridLayout_3.setObjectName("gridLayout_3")
#         self.pushButton_2 = QtWidgets.QPushButton(self.frame_10)
#         self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 40))
#         self.pushButton_2.setStyleSheet("QPushButton{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #d3dae3;\n"
# "    padding: 2px;\n"
# "    background-color: #151a1e;\n"
# "}\n"
# "QPushButton::default{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #FFFFFF;\n"
# "    padding: 2px;\n"
# "    background-color: #151a1e;;\n"
# "}\n"
# "QPushButton:hover{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #d3dae3;\n"
# "    padding: 2px;\n"
# "    background-color: #1c1f1f;\n"
# "}\n"
# "QPushButton:pressed{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #d3dae3;\n"
# "    padding: 2px;\n"
# "    background-color: #2c2f2f;\n"
# "}\n"
# "QPushButton:disabled{\n"
# "    border-style: solid;\n"
# "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
# "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
# "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
# "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #808086;\n"
# "    padding: 2px;\n"
# "    background-color: rgb(142,142,142);\n"
# "}")
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.pushButton_2.clicked.connect(self.dhcp_start)
#         self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
#         self.horizontalLayout.addWidget(self.frame_10)
#         self.frame_11 = QtWidgets.QFrame(self.frame)
#         self.frame_11.setStyleSheet("background-color: rgb(21, 26, 30);\n"
# "border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;")
#         self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.frame_11.setObjectName("frame_10")
#         self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_11)
#         self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
#         self.gridLayout_3.setSpacing(0)
#         self.gridLayout_3.setObjectName("gridLayout_3")
#         self.pushButton_3 = QtWidgets.QPushButton(self.frame_11)
#         self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 40))
#         self.pushButton_3.setStyleSheet("QPushButton{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #d3dae3;\n"
# "    padding: 2px;\n"
# "    background-color: #151a1e;\n"
# "}\n"
# "QPushButton::default{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #FFFFFF;\n"
# "    padding: 2px;\n"
# "    background-color: #151a1e;;\n"
# "}\n"
# "QPushButton:hover{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #d3dae3;\n"
# "    padding: 2px;\n"
# "    background-color: #1c1f1f;\n"
# "}\n"
# "QPushButton:pressed{\n"
# "    border-style: solid;\n"
# "    border-color: #050a0e;\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #d3dae3;\n"
# "    padding: 2px;\n"
# "    background-color: #2c2f2f;\n"
# "}\n"
# "QPushButton:disabled{\n"
# "    border-style: solid;\n"
# "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
# "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
# "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
# "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
# "    border-width: 1px;\n"
# "    border-radius: 5px;\n"
# "    color: #808086;\n"
# "    padding: 2px;\n"
# "    background-color: rgb(142,142,142);\n"
# "}")
#         self.pushButton_3.setObjectName("pushButton_3")
#         self.pushButton_3.clicked.connect(self.ping_check)
#         self.gridLayout_3.addWidget(self.pushButton_3, 0, 0, 1, 1)
#         self.horizontalLayout.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("SELECT TEST CASE")
        self.comboBox.addItem("S_CTC_ID_001")
        self.comboBox.addItem("S_CTC_ID_002")
        self.comboBox.addItem("S_CTC_ID_003")
        self.comboBox.addItem("S_CTC_ID_004")
        self.comboBox.addItem("S_CTC_ID_005")
        self.comboBox.addItem("S_CTC_ID_006")
        self.comboBox.addItem("S_CTC_ID_007")
        self.comboBox.addItem("S_CTC_ID_008")
        self.comboBox.addItem("S_CTC_ID_009")
        self.comboBox.addItem("S_CTC_ID_010")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #1c1f1f;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #2c2f2f;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start_process)
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "S PLANE AUTOMATION"))
        # self.label.setText(_translate("MainWindow", "SELECT A TEST CASE"))
        self.pushButton.setText(_translate("MainWindow", "EXECUTE"))
        # self.pushButton_2.setText(_translate("MainWindow", "START DHCP"))
        # self.pushButton_3.setText(_translate("MainWindow", "PING CHECK"))
    def message(self, s):
        self.plainTextEdit.appendPlainText(s)
    def start_process(self):
        self.T5 = self.comboBox_1.currentText()# SMALL CELL OR MACRO CELL
        if self.T5 == "SMALL_CELL":
            self.T4 = self.comboBox.currentText()
            if self.T4 == 'SELECT TEST CASE':
                msg = QMessageBox()
                msg.setWindowTitle("Error message")
                msg.setText("Please select a test case")
                x = msg.exec_()
            else:
                if self.p is None:
                    self.message("Executing process")
                    self.p = QProcess()
                    self.T4 = self.comboBox.currentText()
                    print(self.T4)
                    self.p.readyReadStandardOutput.connect(self.handle_stdout)
                    self.p.readyReadStandardError.connect(self.handle_stderr)
                    self.p.finished.connect(self.process_finished)  # Clean up once complete.
                    self.p.start("python3", [f'/home/vvdn/SPLANE_SUITE/SMALL_CELL/{self.T4}.py'])
        elif self.T5 == "MACRO_CELL":
            self.T4 = self.comboBox.currentText()
            if self.T4 == 'SELECT TEST CASE':
                msg = QMessageBox()
                msg.setWindowTitle("Error message")
                msg.setText("Please select a test case")
                x = msg.exec_()
            else:
                if self.p is None:
                    self.message("Executing process")
                    self.p = QProcess()
                    self.T4 = self.comboBox.currentText()
                    print(self.T4)
                    self.p.readyReadStandardOutput.connect(self.handle_stdout)
                    self.p.readyReadStandardError.connect(self.handle_stderr)
                    self.p.finished.connect(self.process_finished)  # Clean up once complete.
                    self.p.start("python3", [f'/home/vvdn/SPLANE_SUITE/SMALL_CELL/{self.T4}.py'])
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error message")
            msg.setText("Please select a RU category")
            x = msg.exec_()



    def dhcp_start(self):
        command = "sudo /etc/init.d/isc-dhcp-server restart"
        sudopassword = 'vvdntech'
        os.system('echo %s | sudo %s' % (command, sudopassword))

    def ping_check(self):
        if self.p is None:
            self.p = QProcess()
            self.message("Executing process")
            self.p.readyReadStandardOutput.connect(self.handle_stdout)
            self.p.readyReadStandardError.connect(self.handle_stderr)
            self.p.finished.connect(self.process_finished)  # Clean up once complete.
            self.p.start("python3", ['/home/vvdn/SPLANE_SUITE/ping_check.py'])
        

    def handle_stderr(self):
        data = self.p.readAllStandardError()
        stderr = bytes(data).decode("utf8")
        # Extract progress if it is in the data.
        progress = simple_percent_parser(stderr)
        if progress:
            self.progress.setValue(progress)
        self.message(stderr)

    def handle_stdout(self):
        data = self.p.readAllStandardOutput()
        stdout = bytes(data).decode("utf8")
        self.message(stdout)

    def handle_state(self, state):
        states = {
            QProcess.NotRunning: 'Not running',
            QProcess.Starting: 'Starting',
            QProcess.Running: 'Running',
        }
        state_name = states[state]
        self.message(f"State changed: {state_name}")

    def process_finished(self):
        self.message("Process finished.")
        self.p = None

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
