# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from Menu import Ui_Menu
from PyQt5.QtWidgets import *

class Ui_parameters(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Menu()
        self.ui.setupUi(self.window)
        self.window.show()
        parameters.hide()

        
    def setupUi(self, parameters):

        parameters.setObjectName("parameters")
        parameters.resize(522, 368)
        parameters.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"color: rgb(255, 255, 255);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(parameters)
        self.centralwidget.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"color: rgb(255, 255, 255);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_3.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 4, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_7.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 3, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_5.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 6, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_2.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_4.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        # self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_6.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(21, 26, 30);\n"
"color: rgb(255, 255, 255);\n"
"border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Usr = QtWidgets.QLabel(self.frame_2)
        self.Usr.setStyleSheet("color: rgb(255, 255, 255);")
        self.Usr.setAlignment(QtCore.Qt.AlignCenter)
        self.Usr.setObjectName("Usr")
        self.verticalLayout_2.addWidget(self.Usr)
        self.pss = QtWidgets.QLabel(self.frame_2)
        self.pss.setStyleSheet("color: rgb(255, 255, 255);")
        self.pss.setAlignment(QtCore.Qt.AlignCenter)
        self.pss.setObjectName("pss")
        self.verticalLayout_2.addWidget(self.pss)
        self.NeoIP = QtWidgets.QLabel(self.frame_2)
        self.NeoIP.setStyleSheet("color: rgb(255, 255, 255);")
        self.NeoIP.setAlignment(QtCore.Qt.AlignCenter)
        self.NeoIP.setObjectName("NeoIP")
        self.verticalLayout_2.addWidget(self.NeoIP)
        self.file_path = QtWidgets.QLabel(self.frame_2)
        self.file_path.setStyleSheet("color: rgb(255, 255, 255);")
        self.file_path.setAlignment(QtCore.Qt.AlignCenter)
        self.file_path.setObjectName("file_path")
        self.verticalLayout_2.addWidget(self.file_path)
        self.r_usr = QtWidgets.QLabel(self.frame_2)
        self.r_usr.setStyleSheet("color: rgb(255, 255, 255);")
        self.r_usr.setAlignment(QtCore.Qt.AlignCenter)
        self.r_usr.setObjectName("r_usr")
        self.verticalLayout_2.addWidget(self.r_usr)
        self.r_pss = QtWidgets.QLabel(self.frame_2)
        self.r_pss.setStyleSheet("color: rgb(255, 255, 255);")
        self.r_pss.setAlignment(QtCore.Qt.AlignCenter)
        self.r_pss.setObjectName("r_pss")
        self.verticalLayout_2.addWidget(self.r_pss)
        self.sys_log = QtWidgets.QLabel(self.frame_2)
        self.sys_log.setStyleSheet("color: rgb(255, 255, 255);")
        self.sys_log.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_log.setObjectName("sys_log")
        self.verticalLayout_2.addWidget(self.sys_log)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton.clicked.connect(self.set_params)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #1c1f1f;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #2c2f2f;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame)
        parameters.setCentralWidget(self.centralwidget)

        self.retranslateUi(parameters)
        QtCore.QMetaObject.connectSlotsByName(parameters)
    def set_params(self):
        f = open('/home/vvdn/SPLANE_SUITE/SMALL_CELL/details.json')
        data = json.load(f)
        f1 = open('/home/vvdn/SPLANE_SUITE/MACRO_CELL/details.json')
        data1 = json.load(f1)
        if self.lineEdit.text() =='' or self.lineEdit_2.text() =='' or self.lineEdit_7.text() =='' or self.lineEdit_4.text() =='' or self.lineEdit_5.text() =='' or self.lineEdit_6.text() ==''or self.lineEdit_3.text() =='':
                                                        msg = QMessageBox()
                                                        msg.setWindowTitle("Error message")
                                                        msg.setText("Please Enter the values")
                                                        x = msg.exec_()
        else:
                x = {
                "Username" : self.lineEdit.text(),
                'password' :self.lineEdit_2.text(),
                'File_path' : self.lineEdit_3.text(),
                'root_Username' : self.lineEdit_4.text(),
                'root_password' : self.lineEdit_5.text(),
                'Log_file_name' : self.lineEdit_6.text(),
                'Paragon_IP' : self.lineEdit_7.text(),

                }
                data.update(x)
                def write_json(new_data, filename='/home/vvdn/SPLANE_SUITE/SMALL_CELL/details.json'):
                        with open(filename,'w') as file:
                                json.dump(new_data, file, indent = 4)
                write_json(data)
                data1.update(x)
                def write_json(new_data, filename='/home/vvdn/SPLANE_SUITE/MACRO_CELL/details.json'):
                        with open(filename,'w') as file:
                                json.dump(new_data, file, indent = 4)
                write_json(data1)
                self.openWindow()

    def retranslateUi(self, parameters):
        _translate = QtCore.QCoreApplication.translate
        parameters.setWindowTitle(_translate("parameters", "MainWindow"))
        self.label_8.setText(_translate("parameters", "Parameters Configuration"))
        self.Usr.setText(_translate("parameters", "Username"))
        self.pss.setText(_translate("parameters", "Password"))
        self.NeoIP.setText(_translate("parameters", "paragon IP"))
        self.file_path.setText(_translate("parameters", "File path"))
        self.r_usr.setText(_translate("parameters", "Root Username"))
        self.r_pss.setText(_translate("parameters", "Root password"))
        self.sys_log.setText(_translate("parameters", "System log file name"))
        self.pushButton.setText(_translate("parameters", "Submiit"))


if __name__ == "__main__":
    import sys
    

    app = QtWidgets.QApplication(sys.argv)
    parameters = QtWidgets.QMainWindow()
    ui = Ui_parameters()
    ui.setupUi(parameters)
    parameters.show()
    sys.exit(app.exec_())
